#!/bin/bash

PHP=`which php`;

if [ $? -ne 0 ]; then
	read -p 'Could not find PHP. Path to php executable: ' PHP;
fi

if [ -z "${PHP}" ]; then
	echo 'Could not install. No PHP found.';
	exit -1;
fi

cd `dirname $0`;
$PHP pre-install.php


# install script dependencies as part of pre-install
read -p 'Install mysql scripts? (y/n) [n]: ' INSTALL_MYSQL
case $INSTALL_MYSQL in
		""|n|N|no|NO|No*)
		;;
		*)
			# path to mysql executable
			MYSQL=`which mysql`
			if [ -z "${MYSQL}" ]
			then
				read -p "Mysql not found on path, enter mysql command: " MYSQL
			fi

			# read defaults from existing config
			DEFAULT_HOST=`egrep '^db_hostname = ' ../conf/config.ini | sed 's/^.*=[ ]*//;s/[ ]*$//'`
			DEFAULT_DB=`egrep '^db_name = ' ../conf/config.ini | sed 's/^.*=[ ]*//;s/[ ]*$//'`

			# install db host
			read -p "Mysql hostname [$DEFAULT_HOST]: " MYSQL_HOST
			if [ -z "${MYSQL_HOST}" ]
			then
				MYSQL_HOST=$DEFAULT_HOST;
			fi

			# install db name
			read -p "Mysql database [$DEFAULT_DB]: " MYSQL_DB
			if [ -z "${MYSQL_DB}" ]
			then
				MYSQL_DB=$DEFAULT_DB;
			fi

			# admin db username
			read -p 'Mysql user with permission to run scripts: ' MYSQL_USER
			if [ -z "${MYSQL_USER}" ]
			then
				echo 'No user entered, exiting';
				exit 1;
			fi
			# admin db password
			read -s -p "Password for mysql user '${MYSQL_USER}': " MYSQL_PASS
			echo
			if [ -z "${MYSQL_PASS}" ]
			then
				echo 'No password entered, exiting';
				exit 1;
			fi

			# install scripts
			echo "running getEventIdByFullEventId.sql"
			$MYSQL -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DB < sql/getEventIdByFullEventId.sql
			echo "running currentProducts.sql"
			$MYSQL -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DB < sql/currentProducts.sql
			echo "running auto_summary.sql"
			$MYSQL -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DB < sql/auto_summary.sql
			echo "done"
		;;
esac;


exit 0;
