<?php

// Load the configuration. This will put a $CONFIG array in scope that will
// have all the configured values available to this script.
include_once 'configure.php';

// work in lib directory
chdir(dirname($argv[0]));
$LIB_DIR = $_SERVER['PWD'];
// path specific to this feed app version
$APP_DIR = dirname($LIB_DIR);
$HTDOCS_DIR = $APP_DIR . DIRECTORY_SEPARATOR . 'htdocs';
$CONF_DIR = $APP_DIR . DIRECTORY_SEPARATOR . 'conf';
$HTTPD_CONF_FILE = $CONF_DIR . DIRECTORY_SEPARATOR . 'httpd.conf';

$FEED_PATH = $CONFIG['FEED_PATH'] . '/' . $CONFIG['API_VERSION'];
$FDSN_PATH = $CONFIG['FDSN_PATH'];
$SEARCH_PATH = $CONFIG['SEARCH_PATH'];


// write apache configuration
$HTTPD_CONF = '
## This configuration is auto generated by pre-install
## Manual changes will be overwritten
##

########################################################
# FeedApp: Realtime feeds and search
# Primary contact : Jeremy Fee <jmfee@usgs.gov>
# Secondary contact : Eric Martinez <emartinez@usgs.gov>
########################################################

### PRODUCT SEARCH APP

RewriteEngine on



## EQ Search URL Hijacking

# Only ever offered for v1.0, so just need to redirect that version
RewriteRule ^/earthquakes/feed/v1.0/urlbuilder.php ' . $SEARCH_PATH . '/ [R=301]
RewriteRule ^/earthquakes/eqarchives/epic/ ' . $SEARCH_PATH . '/ [R=301]
RewriteRule ^' . $SEARCH_PATH . '/$ ' . $FEED_PATH . '/search.php [L,PT]
RewriteRule ^' . $SEARCH_PATH . '/(js|css|lib)/(.*) ' . $FEED_PATH . '/$1/$2 [L,PT]

## END: EQ Search URL Hijacking


## DONT ALLOW SEARCH ON EARTHQUAKE, need new split architecture first.
## split architecture routing should eliminate need for this section.

RewriteCond %{HTTP_HOST} earthquake.usgs.gov
RewriteRule ' . $FDSN_PATH . ' - [R=404,L]

## END DONT ALLOW SEARCH ON EARTHQUAKE

## DONT ALLOW FEEDS ON COMCAT, need new split architecture first.
## split architecture routing should eliminate need for this section.

RewriteCond %{HTTP_HOST} comcat.cr.usgs.gov
# but allow images in feeds
RewriteCond $1 !images
RewriteRule ' . $FEED_PATH . '(.*) - [R=404,L]

## END DONT ALLOW FEEDS ON COMCAT


# detail is EVENTID.FORMAT
RewriteRule ^' . $FEED_PATH . '/detail/([^\./]+)\.([^/\.]+)$ ' . $FEED_PATH . '/detail.php?eventid=$1&format=$2 [L,PT]
# summary is PARAMS.FORMAT
RewriteRule ^' . $FEED_PATH . '/summary/([^/]+)\.([^/\.]+)$ ' . $FEED_PATH . '/summary.php?params=$1&format=$2 [L,PT]


# fdsn event webservice
RewriteRule ^' . $FDSN_PATH . '$ ' . $FDSN_PATH . '/ [R=301,L]
RewriteRule ^' . $FDSN_PATH . '/([^/]*)$ ' . $FEED_PATH . '/fdsn.php?method=$1 [L,QSA,PT]

Alias ' . $FEED_PATH . ' ' . $HTDOCS_DIR . '
<Directory ' . $HTDOCS_DIR . '>
	Order allow,deny
	Allow from all
</Directory>

<Location ' . $FEED_PATH . '/>
	SetEnv APP_URL_PATH ' . $FEED_PATH . '
	SetEnv APP_WEB_DIR ' . $HTDOCS_DIR . '
	ExpiresActive on
	ExpiresDefault A60
</Location>
';


file_put_contents($HTTPD_CONF_FILE, $HTTPD_CONF);


?>
